"""
SkyMission Builder - Reporting Module
배치 작업 결과를 시각적인 HTML 리포트로 변환합니다.
"""

import datetime
from pathlib import Path
from typing import List, Dict

HTML_TEMPLATE = """
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <title>SkyMission Builder - 작업 리포터</title>
    <style>
        body {{ font-family: 'Malgun Gothic', sans-serif; line-height: 1.6; color: #333; max-width: 1000px; margin: 0 auto; padding: 20px; background-color: #f4f7f6; }}
        h1 {{ color: #004a99; border-bottom: 2px solid #004a99; padding-bottom: 10px; }}
        .summary {{ background: #fff; padding: 20px; border-radius: 8px; box-shadow: 0 2px 5px rgba(0,0,0,0.1); margin-bottom: 20px; }}
        .summary-grid {{ display: grid; grid-template-columns: repeat(auto-fit, minmax(150px, 1fr)); gap: 10px; }}
        .metric {{ padding: 10px; background: #eef2f3; border-radius: 4px; text-align: center; }}
        .metric-val {{ font-size: 1.5em; font-weight: bold; color: #0078d4; }}
        table {{ width: 100%; border-collapse: collapse; background: #fff; border-radius: 8px; overflow: hidden; box-shadow: 0 2px 5px rgba(0,0,0,0.1); }}
        th, td {{ padding: 12px 15px; text-align: left; border-bottom: 1px solid #ddd; }}
        th {{ background-color: #0078d4; color: white; font-weight: bold; }}
        tr:hover {{ background-color: #f1f1f1; }}
        .status-safe {{ color: #28a745; font-weight: bold; }}
        .status-warning {{ color: #f39c12; font-weight: bold; }}
        .status-danger {{ color: #dc3545; font-weight: bold; }}
        .footer {{ margin-top: 30px; text-align: center; font-size: 0.8em; color: #777; }}
    </style>
</head>
<body>
    <h1>SkyMission Builder - 작업 결과 리포트</h1>
    
    <div class="summary">
        <h3>작업 요약</h3>
        <div class="summary-grid">
            <div class="metric">
                <div>총 미션</div>
                <div class="metric-val">{total}</div>
            </div>
            <div class="metric">
                <div>성공</div>
                <div class="metric-val" style="color: #28a745;">{success}</div>
            </div>
            <div class="metric">
                <div>실패</div>
                <div class="metric-val" style="color: #dc3545;">{failure}</div>
            </div>
            <div class="metric">
                <div>작업 시간</div>
                <div>{timestamp}</div>
            </div>
        </div>
    </div>

    <table>
        <thead>
            <tr>
                <th>파일명</th>
                <th>상태</th>
                <th>GSD (cm)</th>
                <th>Blur (cm)</th>
                <th>속도/고도</th>
                <th>메시지</th>
            </tr>
        </thead>
        <tbody>
            {table_rows}
        </tbody>
    </table>

    <div class="footer">
        Generated by SkyMission Builder v0.1.0 | DJI WPML 1.0.6 Standard
    </div>
</body>
</html>
"""

def generate_report(results: List[Dict], output_dir: Path) -> Path:
    """
    배치 결과를 바탕으로 HTML 리포트를 생성합니다.
    """
    timestamp = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    file_timestamp = datetime.datetime.now().strftime("%Y%m%d_%H%M%S")
    
    total = len(results)
    success = sum(1 for r in results if r['success'])
    failure = total - success
    
    rows = []
    for r in results:
        status_class = f"status-{r.get('status', 'safe')}"
        metrics = r.get('metrics', {})
        
        row = f"""
        <tr>
            <td>{r['name']}</td>
            <td class="{status_class}">{r.get('status', 'N/A').upper()}</td>
            <td>{metrics.get('gsd', '-')}</td>
            <td>{metrics.get('blur', '-')}</td>
            <td>{r.get('speed', '-')}m/s / {r.get('altitude', '-')}m</td>
            <td style="font-size: 0.85em;">{'<br>'.join(r.get('messages', []))}</td>
        </tr>
        """
        rows.append(row)
    
    html_content = HTML_TEMPLATE.format(
        total=total,
        success=success,
        failure=failure,
        timestamp=timestamp,
        table_rows="".join(rows)
    )
    
    report_path = output_dir / f"report_{file_timestamp}.html"
    with open(report_path, "w", encoding="utf-8") as f:
        f.write(html_content)
    
    return report_path
